services:
  - type: web
    name: website-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web_monitor.py
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /health
